name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    php-lint:
        name: PHP Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get changed files
              uses: tj-actions/changed-files@v44.5.5
              with:
                  files: '**/*.php'

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'

            - name: Lint PHP files
              uses: 10up/wpcs-action@stable
              with:
                  enable_warnings: false
                  paths: '.'
                  excludes: 'languages assets'
                  standard: 'WordPress-Extra'
                  use_local_config: 'true'
                  only_changed_files: 'true'
                  only_changed_lines: 'false'
